src/backoffice/Components/ResourceTypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace KubeCMS.Backoffice.Controllers
{
    public class ResourceTypesViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

src/backoffice/Components/SitesViewComponent.cs
using System.IO;
using System.Linq;
using KubeCMS.Backoffice.Options;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace KubeCMS.Backoffice.Controllers
{
    public class SitesViewComponent : ViewComponent
    {
        private readonly BackofficeOptions _options;

        public SitesViewComponent(IOptions<BackofficeOptions> options)
        {
            _options = options.Value;
        }

        public IViewComponentResult Invoke()
        {
            if (Directory.Exists(_options.DataPath))
            {
                var retval = Directory.GetDirectories(_options.DataPath)
                                .Select(Path.GetFileName)
                                .OrderBy(q => q)
                                .ToList();

                return View(retval);
            }

            return View();
        }
    }
}

src/backoffice/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace KubeCMS.Backoffice.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/backoffice/Controllers/SitesController.cs
using System.IO;
using KubeCMS.Backoffice.Options;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace KubeCMS.Backoffice.Controllers
{
    public class SitesController : Controller
    {
        private readonly BackofficeOptions _options;

        public SitesController(IOptions<BackofficeOptions> options)
        {
            _options = options.Value;
        }

        [Route("sites")]
        public IActionResult GetSites()
        {
            return View();
        }

        [Route("sites/{id}")]
        public IActionResult GetSite(string id)
        {
            if (Directory.Exists($"{_options.DataPath}{id}"))
            {
                ViewBag.Site = id;
                return View();
            }

            return NotFound();
        }

        [HttpPost]
        [Route("sites/{id}")]
        public IActionResult PostSite(string id)
        {
            if (!Directory.Exists($"{_options.DataPath}{id}"))
            {
                Directory.CreateDirectory($"{_options.DataPath}{id}");
            }

            return RedirectToAction("GetSite", new { id });
        }
    }
}

src/backoffice/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/Layout.cshtml";
}

src/backoffice/Views/Shared/Components/ResourceTypes/Default.cshtml
<a id="menu-resourcetypes" class="mdl-button mdl-js-button mdl-button--icon material-icons mdl-badge mdl-badge--overlap">
    <i class="material-icons">add</i>
</a>
<ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="menu-resourcetypes">
    <li id="link-add-site" class="mdl-menu__item">Site</li>
</ul>

<dialog id="dialog-add-site" class="mdl-dialog">
    <h4 class="mdl-dialog__title">What is the domain of your new site?</h4>
    <div class="mdl-dialog__content">
        <p>This will be the site's unique identifier. You can change this later if you like or add more domains.</p>
        <form asp-controller="Sites" asp-action="PostSite" method="POST">
            <div class="mdl-textfield mdl-js-textfield">
                <input class="mdl-textfield__input" type="text" id="id" name="id">
                <label class="mdl-textfield__label" for="add-site-domain">Domain...</label>
            </div>
        </form>
    </div>
    <div class="mdl-dialog__actions">
        <button type="submit" class="mdl-button" id="add-site-button" disabled>Create</button>
        <button type="button" class="mdl-button close">Close</button>
    </div>
</dialog>

<script>
    var dialog = document.querySelector('#dialog-add-site');
    var dialogButton = document.querySelector('#link-add-site');

    document.querySelector('#id').addEventListener("keyup", function () {
        var nameInput = document.querySelector('#id').value;
        if (nameInput != "") {
            document.querySelector('#add-site-button').removeAttribute("disabled");
        } else {
            document.querySelector('#add-site-button').setAttribute("disabled", null);
        }
    });

    if (!dialog.showModal) {
      dialogPolyfill.registerDialog(dialog);
    }

    dialogButton.addEventListener('click', function() {
      dialog.showModal();
    });

    dialog.querySelector('.close').addEventListener('click', function() {
      dialog.close();
    });
</script>

src/backoffice/Views/Shared/Components/Sites/Default.cshtml
@model IEnumerable<string>

@if (Model != null && Model.Any())
{
    <a id="menu-sites" class="mdl-button mdl-js-button mdl-button--icon material-icons mdl-badge mdl-badge--overlap">
        <i class="material-icons">language</i>
    </a>
    <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="menu-sites">
        @foreach (var site in Model)
        {
            <li class="mdl-menu__item">
                <a asp-controller="Sites" asp-action="GetSite" asp-route-id="@site">@site</a>
            </li>
        }
    </ul>
}

src/backoffice/Views/Sites/GetSite.cshtml
@{
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer">
    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title mdl-layout-title-muted">Site</span>
        <nav class="mdl-navigation">
            <span class="mdl-navigation__link mdl-navigation__link-muted" href="">@Html.Encode(ViewBag.Site)</span>
        </nav>
        <hr />
        <span class="mdl-layout-title">Drive</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="">Content</a>
            <a class="mdl-navigation__link" href="">Media</a>
            <a class="mdl-navigation__link" href="">Redirects</a>
        </nav>
        <span class="mdl-layout-title">Settings</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="">Domains</a>
            <a class="mdl-navigation__link" href="">Content Templates</a>
            <a class="mdl-navigation__link" href="">Content Types</a>
            <a class="mdl-navigation__link" href="">Media Types</a>
            <a class="mdl-navigation__link" href="">Property Types</a>
            <a class="mdl-navigation__link" href="">Scale</a>
        </nav>
        <span class="mdl-layout-title">Status</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link mdl-navigation__link-active" href="">Dashboard</a>
            <a class="mdl-navigation__link" href="">Publisher</a>
            <a class="mdl-navigation__link" href="">Storage</a>
            <a class="mdl-navigation__link" href="">Versions</a>
        </nav>
    </div>
    <main class="mdl-layout__content">
        <div class="page-content">
        </div>
    </main>
</div>

src/backoffice/Views/Sites/GetSites.cshtml
@{
    Layout = "~/Views/Shared/Layout.cshtml";
}